-- Optional per-offering start-time restrictions.
-- An empty array means the offering may use every start generated by the
-- weekly schedule. Otherwise, only the listed local studio times are offered.

alter table offerings
  add column if not exists allowed_start_times time[] not null default '{}';

comment on column offerings.allowed_start_times is
  'Allowed local booking start times. Empty means unrestricted.';
